package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'run_client_tests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("run_client_tests")) {
    check(description == "") {
        "Unexpected description: '$description'"
    }
    description = "test"
}
