package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    check(description == "") {
        "Unexpected description: '$description'"
    }
    description = "Calypso projects"

    params {
        add {
            param("teamcity.git.fetchAllHeads", "true")
        }
    }
}
