package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = 'fd7c1bc8-1475-4f0c-b8a1-f0ca38bb2097'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("fd7c1bc8-1475-4f0c-b8a1-f0ca38bb2097"))

