package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = '60015d31-ebf4-432e-afc6-7b204f6784c9'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("60015d31-ebf4-432e-afc6-7b204f6784c9"))

