package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the template with absolute id = '69184c2d-719b-4844-8088-925aeebe578a'
from your code, and delete the patch script.
*/
deleteTemplate(AbsoluteId("69184c2d-719b-4844-8088-925aeebe578a"))

